version: "3.9"

services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: carboncore
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports: ["5432:5432"]

  redis:
    image: redis:7
    ports: ["6379:6379"]

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    volumes:
      - ./backend:/code
    environment:
      DATABASE_URL: postgresql+asyncpg://postgres:postgres@db:5432/carboncore
      REDIS_URL: redis://redis:6379/0
    depends_on: [db, redis]
    ports: ["8000:8000"]

  celery:
    build:
      context: .
      dockerfile: backend/Dockerfile
    command: celery -A app.tasks.worker worker -B --loglevel=info
    volumes:
      - ./backend:/code
    environment:
      DATABASE_URL: postgresql+asyncpg://postgres:postgres@db:5432/carboncore
      REDIS_URL: redis://redis:6379/0
    depends_on: [backend, redis]
