version: "3.9"

services:
  backend:
    # hot-reload + live code
    command:
      ["poetry", "run", "uvicorn",
       "backend.app.main:app",
       "--host", "0.0.0.0",
       "--port", "8000",
       "--reload"]
    volumes:
      - ./backend:/app/backend
    # match host UID/GID so non-root user can read mounted files
    user: "${UID:-1000}:${GID:-1000}"

  celery:
    build:
      context: .
      dockerfile: backend.Dockerfile
    entrypoint: ["/usr/local/bin/entrypoint.sh"]
    command: ["celery", "-A", "backend.app.worker", "worker", "-l", "info"]
    env_file: .env
    depends_on:
      backend:
        condition: service_healthy
      redis:
        condition: service_healthy
      db:
        condition: service_healthy
    volumes:
      - ./backend:/app/backend      # allows code edits; restart worker to reload

