#############################################################
# docker-compose.yml – CarbonCore full stack
# (Postgres, Redis, Tempo, FastAPI backend, Celery, React UI)
#############################################################

services:
  # ───────────── data plane ─────────────
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: carboncore
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  tempo:                # OpenTelemetry trace collector
    image: grafana/tempo:2.7.2
    command: [ "-config.file=/etc/tempo.yaml" ]
    volumes:
      - ./docker/tempo/tempo.yaml:/etc/tempo.yaml:ro
    ports:
      - "4318:4318"      # OTLP HTTP
      - "4317:4317"      # OTLP gRPC (optional)

  # ───────────── compute plane ──────────
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    volumes:
      - ./backend:/code                  # live-reload during dev
    env_file:
      - .env.development                 # user-editable defaults
    environment:
      # core connectivity
      DATABASE_URL: postgresql+asyncpg://postgres:postgres@db:5432/carboncore
      REDIS_URL: redis://redis:6379/0
      # live carbon providers
      # ELECTRICITYMAPS_TOKEN: "Z5NJGQ28hQq28m4NLsvu"
      # ELECTRICITYMAPS_API_KEY: "Z5NJGQ28hQq28m4NLsvu"
      # WATTTIME_USERNAME: "carboncore"
      # WATTTIME_PASSWORD: "Carboncore123!"

      ELECTRICITYMAPS_TOKEN:  ${ELECTRICITYMAPS_TOKEN:-dummy-token}
      ELECTRICITYMAPS_API_KEY: ${ELECTRICITYMAPS_API_KEY:-dummy-token}   # optional, same value
      WATTTIME_USERNAME:      ${WATTTIME_USERNAME:-dummy}
      WATTTIME_PASSWORD:      ${WATTTIME_PASSWORD:-dummy}

      # observability (disable traces locally)
      OTEL_TRACES_EXPORTER: none
    depends_on:
      - db
      - redis
      - tempo
    ports:
      - "8000:8000"

  celery:
    build:
      context: .
      dockerfile: backend/Dockerfile
    command: celery -A app.tasks.worker worker -B --loglevel=info
    volumes:
      - ./backend:/code
    env_file:
      - .env.development
    environment:
      DATABASE_URL: postgresql+asyncpg://postgres:postgres@db:5432/carboncore
      REDIS_URL: redis://redis:6379/0
      # ELECTRICITYMAPS_TOKEN: "Z5NJGQ28hQq28m4NLsvu"
      # ELECTRICITYMAPS_API_KEY: "Z5NJGQ28hQq28m4NLsvu"
      # WATTTIME_USERNAME: "carboncore"
      # WATTTIME_PASSWORD: "Carboncore123!"

      ELECTRICITYMAPS_TOKEN:  ${ELECTRICITYMAPS_TOKEN:-dummy-token}
      ELECTRICITYMAPS_API_KEY: ${ELECTRICITYMAPS_API_KEY:-dummy-token}   # optional, same value
      WATTTIME_USERNAME:      ${WATTTIME_USERNAME:-dummy}
      WATTTIME_PASSWORD:      ${WATTTIME_PASSWORD:-dummy}


      
      OTEL_TRACES_EXPORTER: none
    depends_on:
      - backend
      - redis
      - tempo

  # ─────────── optional front-end ───────────
  # web:
  #   build:
  #     context: .
  #     dockerfile: web/Dockerfile
  #   command: pnpm dev --port 3000
  #   volumes:
  #     - ./web:/app
  #   depends_on:
  #     - backend
  #   ports:
  #     - "3000:3000"
