services:
  db:
    image: postgres:16
    environment:
      POSTGRES_PASSWORD: postgres
    volumes: ["dbdata:/var/lib/postgresql/data"]
    ports: ["5432:5432"]

  redis:
    image: redis:7
    ports: ["6379:6379"]

  backend:
    build:
      context: .
      dockerfile: docker/backend.Dockerfile
    command: ["bash", "docker/entrypoint.sh", "uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
    volumes: ["./backend:/code"]
    env_file: .env.dev
    depends_on: [db, redis]

  celery:
    build:
      context: .
      dockerfile: docker/backend.Dockerfile
    command: ["celery", "-A", "app.tasks", "worker", "--loglevel=info"]
    volumes: ["./backend:/code"]
    env_file: .env.dev
    depends_on: [backend, redis]

  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    command: ["pnpm", "dev", "-p", "3000"]
    volumes: ["./web:/app"]
    env_file: ../.env.dev
    depends_on: [backend]
    ports: ["3000:3000"]

volumes:
  dbdata:
