services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_PASSWORD: postgres
    ports: ["5432:5432"]

  redis:
    image: redis:7-alpine
    ports: ["6379:6379"]

  backend:
    build: ./backend
    environment:
      DATABASE_URL: postgresql+asyncpg://postgres:postgres@db:5432/carboncore
      REDIS_URL: redis://redis:6379/0
    volumes: ["./backend:/code"]
    depends_on: [db, redis]
    ports: ["8000:8000"]

  web:
    build: ./web
    environment:
      NEXT_PUBLIC_API_URL: http://backend:8000
    volumes: ["./web:/app"]
    depends_on: [backend]
    ports: ["3000:3000"]
