version: "3.9"

services:
  db:
    image: postgres:16
    env_file: .env
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "carboncore"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 5

  backend:
    build:
      context: .
      dockerfile: backend.Dockerfile
    env_file: .env
    ports: ["8000:8000"]
    entrypoint: ["/usr/local/bin/entrypoint.sh"]
    # **NO command override in prod** (gunicorn runs from Dockerfile)
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    read_only: true
    security_opt:
      - no-new-privileges:true

