version: "3.9"
services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_PASSWORD: postgres
    ports: ["5432:5432"]

  redis:
    image: redis:7-alpine
    ports: ["6379:6379"]

  backend:
    build: ./backend
    command: uvicorn app.main:app --host 0.0.0.0 --reload
    volumes: ["./backend:/code"]
    environment:
      - DATABASE_URL=postgresql+asyncpg://postgres:postgres@db:5432/carboncore
      - REDIS_URL=redis://redis:6379/0
    ports: ["8000:8000"]
    depends_on: [db, redis]

  web:
    build: ./web
    command: pnpm dev -p 3000
    volumes: ["./web:/app"]
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8000
    ports: ["3000:3000"]
    depends_on: [backend]
