services:
# ─────────────────────────────────────────────────────────────────
  db:
    image: postgres:16
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - dbdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:7
    ports:
      - "6379:6379"

# ─────────────────────────────────────────────────────────────────
  backend:
    build:
      context: .
      dockerfile: backend.Dockerfile
    command: >
      bash -c "
        poetry run alembic upgrade head &&
        poetry run uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
      "
    volumes:
      - ./backend:/app                # live reload for API code
    env_file: .env.local              # create or remove this line
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis

# ─────────────────────────────────────────────────────────────────
  celery:
    build:
      context: .
      dockerfile: worker.Dockerfile    # ← NEW, replaces backend.Dockerfile
    volumes:
      - ./backend:/app
    env_file: .env.local               # create or remove this line
    depends_on:
      - backend
      - redis

# ─────────────────────────────────────────────────────────────────
  web:
    build:
      context: .
      dockerfile: frontend.Dockerfile  # ← NEW path
    environment:
      - CHOKIDAR_USEPOLLING=true       # keep hot-reload happy on macOS
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  dbdata:
