[tool.poetry]
name = "carboncore-backend"
version = "0.1.0"
description = ""
authors = ["you"]

[tool.poetry.dependencies]
python = "^3.12"
fastapi = "^0.111"
uvicorn = {extras = ["standard"], version = "^0.30"}
sqlmodel = "^0.0.16"
asyncpg = "^0.29"
aiocache = "^0.12"
httpx = "^0.27"
celery = "^5.4"
python-dotenv = "^1.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
