[tool.poetry]
name = "carboncore-backend"
version = "0.1.0"
description = "CarbonCore API kernel"
authors = ["You <you@example.com>"]

[tool.poetry.dependencies]
python = "^3.12"
fastapi = "^0.111"
uvicorn = {extras = ["standard"], version = "^0.30"}
sqlmodel = "^0.0.16"
asyncpg = "^0.29"
aiocache = "^0.12"
httpx = "^0.27"
celery = "^5.4"
python-dotenv = "^1.0"
pydantic = "^2.7"

[tool.poetry.group.dev.dependencies]
pytest = "^8.2"
pytest-asyncio = "^0.23"
ruff = "^0.4"
mypy = "^1.10"
