metrics:
  wal_directory: /tmp/agent
  global:
    scrape_interval: 15s
  configs:
    - name: default
      scrape_configs:
        - job_name: api
          static_configs:
            - targets: ['backend:8000']
