import '@/src/styles/tokens.css';
import '@/src/styles/globals.css';
import { ThemeProvider } from 'next-themes';
export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
};
export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html>
      <body>
        <ThemeProvider attribute="class" defaultTheme="system">
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
