import '@/styles/tokens.css'
import '@/styles/globals.css'
import BottomNav from '@/components/mobile/BottomNav'
import { Providers } from '@/components/Providers'

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
};
export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html>
      <head>
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <meta name="color-scheme" content="light dark" />
      </head>
      <body>
        <Providers>{children}</Providers>
        <BottomNav />
      </body>
    </html>
  )
}
