import '@/styles/tokens.css';
import '@/styles/globals.css';
import { ThemeProvider } from 'next-themes';
import { QueryClient, QueryClientProvider } from '@tanstack/react-query';
import BottomNav from '@/components/mobile/BottomNav';
import { initAnalytics, analytics } from '@/lib/analytics';
import { useEffect } from 'react';
import ConsentBanner from '@/components/ConsentBanner';

const client = new QueryClient();
export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
};
export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  initAnalytics();
  useEffect(()=>{ analytics.page(window.location.pathname); },[]);
  return (
    <html>
      <head>
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <meta name="color-scheme" content="light dark" />
      </head>
      <body>
        <ThemeProvider attribute="class" defaultTheme="system">
          <QueryClientProvider client={client}>{children}</QueryClientProvider>
        </ThemeProvider>
        <BottomNav />
        <ConsentBanner />
      </body>
    </html>
  );
}
