"""
CarbonCore FastAPI entry-point  (v0.2.0-frozen)
──────────────────────────────────────────────
• Secure Headers, CORS, global SlowAPI rate-limiting
• JSON logs via core.logging.init_logging
• OTEL traces (auto-disabled if Tempo absent)
• Prometheus /metrics (gzip) via Instrumentator
• Global Pagination (fastapi_pagination)
• Health-/ready probes & blue-green root-path support
"""

from __future__ import annotations

# ───────────── stdlib ─────────────
from contextlib import asynccontextmanager
from datetime import UTC, datetime
from importlib import import_module
from typing import Final, Any

# ───────────── 3rd-party ─────────────
import structlog
import uvicorn
from fastapi import FastAPI, Request, Response, APIRouter
from fastapi.middleware.cors import CORSMiddleware
from fastapi_pagination import add_pagination
from prometheus_fastapi_instrumentator import Instrumentator
from starlette.middleware import Middleware

# ───────────── internal ─────────────
from app.core.logging import init_logging
from app.core.deps import engine, init_db
from app.core.settings import settings
from app.core.otel import init_otel
from app.core.ratelimit import (
    configure as rl_configure,
    attach as attach_rate_limit,
    limiter,
)
from app.middleware.secure_headers import SecureHeadersMiddleware
from app.registry import registry     # alias auto-generated by gen_registry.py

# ───────────── rate-limit defaults ─────────────
rl_configure(default_limits=["1/minute"])

# ───────────── logging bootstrap ─────────────
init_logging()
log = structlog.get_logger()

# ───────────── lifespan ─────────────
@asynccontextmanager
async def lifespan(_: FastAPI):
    log.info("lifespan.start", env=getattr(settings, "ENV", "dev"))
    await init_db()
    yield
    log.info("lifespan.stop")

# ───────────── middleware list ─────────────
MIDDLEWARE: Final[list[Middleware]] = []
if getattr(settings, "SECURE_HEADERS", True):
    MIDDLEWARE.append(Middleware(SecureHeadersMiddleware))

# ───────────── FastAPI factory ─────────────
app = FastAPI(
    version=getattr(settings, "BUILD_SHA", None) or "0.2.0-frozen",
    docs_url="/",
    redoc_url=None,
    root_path=f"/{settings.BLUE_GREEN_COLOR}"
    if getattr(settings, "BLUE_GREEN_COLOR", "")
    else "",
    lifespan=lifespan,
    middleware=MIDDLEWARE,
)

# ───────────── CORS (wide-open) ─────────────
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

# ───────────── Plug-in routing ─────────────
for pm in registry.values():
    for route in pm.routes:
        # Case 1 • APIRouter
        if isinstance(route, APIRouter):
            app.include_router(route, prefix=f"/{pm.id}")
            log.info("router.mounted", plugin=pm.id, router=route.__class__.__name__)
            continue

        # Case 2 • Lightweight route spec
        if not getattr(route, "path", None):
            log.warning(
                "route.skipped",
                plugin=pm.id,
                reason="no path defined on route object",
            )
            continue

        try:
            module_path, obj_name = route.handler.split(":")
            target: Any = getattr(import_module(module_path), obj_name)
        except Exception as exc:                       # ImportError / ValueError …
            log.error("route.import_failed", plugin=pm.id, err=str(exc))
            continue

        # Always prefix with /<plugin-id>
        prefix = f"/{pm.id}"
        final_path = (
            f"{prefix}{route.path}"
            if route.path.startswith("/")
            else f"{prefix}/{route.path}"
        )

        app.add_api_route(
            final_path,
            target,
            methods=[route.method],
            name=f"{pm.id}:{obj_name}",
            include_in_schema=True,
        )
        log.info("route.mounted", plugin=pm.id, path=final_path)

# ───────────── helpers ─────────────
attach_rate_limit(app)
add_pagination(app)

# ───────────── probes ─────────────
@limiter.limit("1/minute", key_func=lambda *_a, **_k: "health-burst")
@app.get("/healthz", include_in_schema=False)
async def healthz(request: Request) -> dict[str, str]:   # ← request param needed by SlowAPI
    return {"status": "ok", "ts": datetime.now(UTC).isoformat(timespec="seconds")}

@app.get("/readyz", include_in_schema=False)
async def readyz() -> dict[str, str]:
    return {
        "status": "ready",
        "instance": getattr(settings, "INSTANCE_ID", "local"),
        "color": getattr(settings, "BLUE_GREEN_COLOR", "default"),
    }

# ───────────── Prometheus ─────────────
if getattr(settings, "ENABLE_METRICS", True):
    Instrumentator().instrument(app).expose(
        app, endpoint="/metrics", include_in_schema=False, should_gzip=True
    )
    log.info("prometheus.enabled")

# ───────────── OpenTelemetry ─────────────
if getattr(settings, "ENABLE_TRACING", False):
    try:
        init_otel(app, engine)
        log.info("otel.enabled")
    except Exception as exc:                            # pragma: no cover
        log.warning("otel.disabled", err=str(exc))

log.info("app.initialised")

# ───────────── Local dev runner ─────────────
if __name__ == "__main__":                              # pragma: no cover
    uvicorn.run(
        "app.main:app",
        host="0.0.0.0",
        port=8000,
        reload=True,
        reload_includes=["*.py"],
    )
