name: CD – build, scan, blue-green deploy
on:
  push:
    branches: [main]

env:
  REGISTRY: ghcr.io/${{ github.repository_owner }}
  IMAGE: carboncore-api

jobs:
  build:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
    - uses: actions/checkout@v4

    - name: Set up QEMU & Buildx
      uses: docker/setup-qemu-action@v3
    - uses: docker/setup-buildx-action@v3

    - name: Login to GHCR
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build & push multi-arch image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: docker/api.Dockerfile
        push: true
        tags: ${{ env.REGISTRY }}/${{ env.IMAGE }}:${{ github.sha }}

    - name: Trivy scan
      uses: aquasecurity/trivy-action@v0.18.0
      with:
        image-ref: ${{ env.REGISTRY }}/${{ env.IMAGE }}:${{ github.sha }}
        ignore-unfixed: true

    - name: Cosign sign
      uses: sigstore/cosign-installer@v3
    - run: cosign sign --yes ${{ env.REGISTRY }}/${{ env.IMAGE }}@${{ steps.build.outputs.digest }} \
        --key env://COSIGN_PRIVATE_KEY
      env:
        COSIGN_PRIVATE_KEY: ${{ secrets.COSIGN_KEY }}

    - name: Deploy to Fly (blue-green)
      uses: superfly/flyctl-actions@1.5
      with:
        args: "deploy --image ${{ env.REGISTRY }}/${{ env.IMAGE }}:${{ github.sha }} --strategy bluegreen --wait-timeout 120"
      env:
        FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

    - name: Health check
      run: |
        for i in {1..10}; do
          curl -fsSL https://api.yourapp.com/health && exit 0
          sleep 10
        done
        echo "Health check failed" && exit 1

    - name: Rollback on failure
      if: failure()
      run: flyctl releases rollback -y
      env:
        FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
