name: ci

on:
  push: {branches: ["main"]}
  pull_request: {}

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with: {python-version: "3.12"}
      - name: Poetry install & test
        run: |
          pip install "poetry==1.8.*"
          poetry install --with test --no-interaction
          poetry run pytest

  build-and-push:
    needs: unit-test
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      security-events: write
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - id: build
        uses: docker/build-push-action@v6
        with:
          context: .
          file: backend.Dockerfile
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
          outputs: type=registry,digest-file=digest.txt
      - name: Trivy scan
        uses: aquasecurity/trivy-action@v0.20
        with:
          image-ref: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}@${{ steps.build.outputs.digest }}
          exit-code: 1
      - name: Export digest
        run: echo "IMAGE_DIGEST=$(cat digest.txt)" >> $GITHUB_ENV
