name: build-test-publish

on:
  push:
    branches: [main]
  pull_request:

permissions:
  contents: read
  id-token: write   # needed for keyless cosign

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.12'
        cache: 'poetry'
    - uses: snok/install-poetry@v1
    - name: Install deps & test
      run: |
        poetry install
        poetry run pytest -q
    - name: Check missing migrations
      run: |
        poetry run alembic revision --autogenerate --check || \
          (echo "::error::Uncommitted migration detected" && exit 1)

  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    # ---------- Build & push images ----------
    - name: Login to GHCR
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build & push backend
      uses: docker/build-push-action@v5
      with:
        context: .
        file: backend.Dockerfile
        tags: ghcr.io/${{ github.repository }}/backend:${{ github.sha }}
        push: true
        provenance: false   # provenance will be added after signing

    - name: Build & push frontend
      uses: docker/build-push-action@v5
      with:
        context: .
        file: frontend.Dockerfile
        tags: ghcr.io/${{ github.repository }}/frontend:${{ github.sha }}
        push: true
        provenance: false

    # ---------- Sign images ----------
    - name: Sign images with cosign
      uses: sigstore/cosign-installer@v3
    - run: |
        cosign sign --yes ghcr.io/${{ github.repository }}/backend:${{ github.sha }}
        cosign sign --yes ghcr.io/${{ github.repository }}/frontend:${{ github.sha }}
      env:
        COSIGN_EXPERIMENTAL: 1
        COSIGN_YES: "true"

    # ---------- Generate SBOM ----------
    - name: Create SBOM
      uses: anchore/sbom-action@v0.16.0
      with:
        image: ghcr.io/${{ github.repository }}/backend:${{ github.sha }}

    # ---------- Upload artifacts ----------
    - uses: actions/upload-artifact@v4
      with:
        name: backend-sbom
        path: sbom.spdx.json
