name: nightly-load
on:
  schedule:
    - cron: '0 3 * * *'   # 03:00 UTC every night

jobs:
  load:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: grafana/k6-action@v0.3.1
        with:
          filename: infra/k6/load.js
          flags: --vus 500 --duration 5m
