name: Registry check
on: [push]
jobs:
  gen-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: pip install -r backend/requirements.txt || pip install -r backend/requirements.txt
      - run: python scripts/gen_registry.py
      - run: npm i -g pnpm
      - run: pnpm install --filter web...
      - run: pnpm ts-node web/gen-registry.ts
      - run: pnpm build --filter web...
